=== Tobkubos/SEMESTR-6/XML/untitled/zad6.dtd
<!ELEMENT artykul (autor|tytul|seria|data-publikacji|opis)*>
        <!ELEMENT autor (imie|nazwisko)*>
        <!ELEMENT imie (#PCDATA)>
        <!ELEMENT nazwisko (#PCDATA)>
        <!ELEMENT tytul (#PCDATA)>
        <!ATTLIST tytul
                strona CDATA #REQUIRED>
        <!ELEMENT seria (#PCDATA)>
        <!ATTLIST seria
                strona CDATA #REQUIRED>
        <!ELEMENT data-publikacji (#PCDATA)>
        <!ELEMENT opis (#PCDATA)>

=== Tobkubos/SEMESTR-6/XML/untitled/zad6.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE artykul SYSTEM "zad6.dtd">


<artykul>
    <autor>
        <imie>Grzegorz</imie>
        <nazwisko>Pełechaty</nazwisko>
    </autor>
    <tytul strona="http://www.abc.com/paper1">Jądro Systemu Operacyjnego</tytul>
    <seria strona="http://www.abc.com/os.html">Systemy operacyjne</seria>
    <data-publikacji>2006-06-18</data-publikacji>
    <opis>pokazuje jak napisać własny system
        operacyjny. Omawia zarządzanie pamięcią oraz przerwania w czasie
        rzeczywistym. Porusza również podstawowe zagadnienia tryby chronionego.
        </opis>
</artykul>
