=== Tobkubos/SEMESTR-6/XML/untitled/SCHEMA/SCHEMA_3.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="spis">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="osoba" maxOccurs="3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="imie" type="xs:string"/>
                            <xs:element name="nazwisko" type="xs:string"/>
                            <xs:element name="wiek" type="xs:integer">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tobkubos/SEMESTR-6/XML/untitled/SCHEMA/zad_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<spis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="SCHEMA_3.xsd">
    <osoba>
        <imie>Marek</imie>
        <nazwisko>Nowak</nazwisko>
        <wiek>1</wiek>
    </osoba>
    <osoba>
        <imie>Tomasz</imie>
        <nazwisko>Pawlak</nazwisko>
        <wiek>100</wiek>
    </osoba>
    <osoba>
        <imie>Piotr</imie>
        <nazwisko>Kaczkowski</nazwisko>
        <wiek>27</wiek>
    </osoba>
</spis>
