=== Tobkubos/SEMESTR-6/XML/untitled/SCHEMA/SCHEMA_4_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="spis_publikacji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="publikacja" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tytul" type="xs:string"/>
                            <xs:element name="dzial" type="xs:string" minOccurs="0"/>
                            <xs:element name="wydawnictwo" type="xs:string" minOccurs="0"/>
                            <xs:element name="czasopismo" type="xs:string" minOccurs="0"/>
                            <xs:element name="rok" type="xs:integer"/>
                            <xs:element name="autorzy">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="autor" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="imie" type="xs:string" use="required"/>
                                                <xs:attribute name="nazwisko" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="tom" type="xs:integer" use="optional"/>
                        <xs:attribute name="numer" type="xs:integer" use="optional"/>
                        <xs:attribute name="strona" type="xs:integer" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tobkubos/SEMESTR-6/XML/untitled/SCHEMA/zad_4_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<spis_publikacji xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="SCHEMA_4_2.xsd">
    <publikacja tom="4" numer="3">
        <tytul>Struktura Sieci i adresowanie</tytul>
        <dzial>Zagadnienia Informatyczne</dzial>
        <rok>2004</rok>
        <autorzy>
            <autor imie="Łukasz" nazwisko="Kowalski"/>
            <autor imie="Tomasz" nazwisko="Szczepaniak"/>
        </autorzy>
    </publikacja>

    <publikacja>
        <tytul>Matematyka Dyskretna</tytul>
        <dzial>Matematyka dla Politechnik</dzial>
        <wydawnictwo>Wydawnictwa Naukowe PWN</wydawnictwo>
        <rok>2003</rok>
        <autorzy>
            <autor imie="Tomasz" nazwisko="Żakowski"/>
            <autor imie="Witold" nazwisko="Żakowski"/>
        </autorzy>
    </publikacja>

    <publikacja>
        <tytul>Gramatyka Angielska</tytul>
        <wydawnictwo>Wydawnictwa Szkolne</wydawnictwo>
        <rok>2006</rok>
        <autorzy>
            <autor imie="Bronisława" nazwisko="Jasińska"/>
            <autor imie="Janina" nazwisko="Nowak"/>
            <autor imie="Monika" nazwisko="Wojciechowska"/>
        </autorzy>
    </publikacja>

    <publikacja tom="95" strona="479">
        <tytul>Positron Annihiolation in Solid and Liquid Bi40Sn60 Alloy</tytul>
        <czasopismo>Acta Physica Polonica</czasopismo>
        <rok>1987</rok>
        <autorzy>
            <autor imie="Stanisław" nazwisko="Chabik"/>
            <autor imie="Wanda" nazwisko="Rudzińska"/>
            <autor imie="Marek" nazwisko="Szuszkiewicz"/>
        </autorzy>
    </publikacja>

</spis_publikacji>
