=== Tobkubos/SEMESTR-6/XML/untitled/XSD_2/XSD_2_8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="imie"/>
    <xs:element name="nazwisko"/>

    <xs:complexType name="dokument">
        <xs:choice>
            <xs:element name="paszport" type="InformacjeDodatkowe"/>
            <xs:element name="dowód" type="InformacjeDodatkowe"/>
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="InformacjeDodatkowe">
        <xs:attribute name="numer_dokumentu" use="required"/>
        <xs:attribute name="kraj" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MiejscowoscKodPocztowy">
        <xs:simpleContent>
            <xs:extension base="Nazwa">
                <xs:attribute ref="kodPocztowy" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="Nazwa">
        <xs:restriction base="xs:string">
            <xs:maxLength value="30"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="KodPocztowy">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}-\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:attribute name="kodPocztowy" type="KodPocztowy"/>

    <xs:simpleType name="Plec">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mężczyzna"/>
            <xs:enumeration value="kobieta"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="osoba">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nazwisko"/>
                <xs:element ref="imie" minOccurs="1" maxOccurs="2"/>
                <xs:element name="pesel">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d{11}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="miejscowosc" type="MiejscowoscKodPocztowy"/>
                <xs:element name="dokument" type="dokument"/>
            </xs:sequence>
            <xs:attribute name="plec" type="Plec" use="required"/>
            <xs:attribute name="stan_cywilny" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="kawaler/panna"/>
                        <xs:enumeration value="żonaty/mężatka"/>
                        <xs:enumeration value="wdowiec/wdowa"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>


    <xs:element name="spis_osob">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="osoba" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tobkubos/SEMESTR-6/XML/untitled/XSD_2/xsd_2_8.xml
<?xml version="1.0" encoding="UTF-8"?>
<spis_osob xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="XSD_2_8.xsd">

<osoba plec="kobieta" stan_cywilny="wdowiec/wdowa">
    <nazwisko>qwe</nazwisko>
    <imie>qwe</imie>
    <pesel>12345678911</pesel>
    <miejscowosc kodPocztowy="65-670"></miejscowosc>
    <dokument>
        <dowód numer_dokumentu="1231313" kraj="PL">aaaaaaaaaa</dowód>
    </dokument>
</osoba>
</spis_osob>
